#kt_incentives_config

#config
REFRACTED_LP_RATIO_DELTA_LOWER_BOUND = 0.9
YIELD_TOKEN_ALLOCATION_MAX = 0.25
YIELD_TOKEN_ALLOCATION_MIN = 0
YIELD_TOKEN_ALLOCATION_INCREASE_STEP_SIZE = 0.025
YIELD_TOKEN_ALLOCATION_DECREASE_STEP_SIZE = 0.025
PT_LP_RATIO_DELTA_LOWER_BOUND = 0.9
